services:
  redis:
    image: "redis:alpine"
    

  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.compose.local
    container_name: api
    volumes:
      - .:/code
      - static_volume:/code/staticfiles
      - media_volume:/code/mediafiles
    ports:
      - "80:8000"
    restart: always
    networks:
      - commonnet
    depends_on:
      - db
      - redis-cache